#!/usr/bin/env bash
# Build pre-compiled TypeScript declarations for cross-resolution compatibility.
#
# The Convex package uses moduleResolution: "Bundler". When consumers use
# moduleResolution: "NodeNext" (e.g., the HQ agent), TypeScript hits TS2589
# (type instantiation depth exceeded) trying to infer DataModel types.
#
# This script pre-compiles declarations under Bundler resolution, then creates
# JS stubs so NodeNext resolution can find the .d.ts sidecar files.
#
# It also creates dist/agent/ — a simplified entry point for the HQ agent
# that types `api` and `internal` as `any` to avoid the FilterApi<ApiFromModules<...>>
# depth limit. The agent uses cast() for all Convex function calls anyway.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PKG_DIR="$(dirname "$SCRIPT_DIR")"

cd "$PKG_DIR"

echo "==> Cleaning dist/"
rm -rf dist

echo "==> Generating declarations (Bundler resolution)..."
npx tsc -p tsconfig.build.json

echo "==> Copying _generated/ files..."
mkdir -p dist/convex/_generated
cp convex/_generated/api.d.ts dist/convex/_generated/
cp convex/_generated/api.js dist/convex/_generated/
cp convex/_generated/server.d.ts dist/convex/_generated/
cp convex/_generated/server.js dist/convex/_generated/
cp convex/_generated/dataModel.d.ts dist/convex/_generated/

echo "==> Creating JS stubs for NodeNext resolution..."
# For each .d.ts in dist/ (excluding _generated which already has .js),
# create an empty .js stub so NodeNext can resolve module.js → module.d.ts
find dist -name "*.d.ts" -not -path "*/node_modules/*" | while read -r dts_file; do
  # Skip .d.ts.map files
  if [[ "$dts_file" == *.d.ts.map ]]; then
    continue
  fi

  js_file="${dts_file%.d.ts}.js"
  if [ ! -f "$js_file" ]; then
    # Create empty JS stub — only exists for NodeNext module resolution
    echo "// Type stub for NodeNext resolution — see .d.ts for types" > "$js_file"
  fi
done

echo "==> Creating agent-specific entry point (api: any)..."
mkdir -p dist/agent
cat > dist/agent/index.d.ts << 'AGENT_DTS'
/**
 * Agent-specific type declarations for @repo/convex.
 *
 * Under NodeNext resolution, the full FilterApi<ApiFromModules<{30+ modules}>>
 * type exceeds TypeScript's instantiation depth limit (TS2589). This entry
 * point exports `api` and `internal` as opaque types, since the HQ agent
 * uses cast() for all Convex function calls anyway.
 *
 * Server types (query, mutation, etc.) and DataModel are re-exported from
 * the pre-compiled Bundler declarations where they resolve correctly.
 *
 * Generated by: packages/convex/scripts/build-types.sh
 */
export declare const api: any;
export declare const internal: any;
export * from "../convex/_generated/server";
export type * from "../convex/_generated/dataModel";
AGENT_DTS

cat > dist/agent/index.js << 'AGENT_JS'
// Runtime re-export — actual types in index.d.ts
export { api, internal } from "../../index.ts";
AGENT_JS

echo "==> Declaration build complete!"
echo "    $(find dist -name '*.d.ts' -not -name '*.d.ts.map' | wc -l | tr -d ' ') declaration files"
echo "    $(find dist -name '*.js' | wc -l | tr -d ' ') JS stubs"
